USE master
GO
ALTER DATABASE  test_base
REMOVE FILE file4
GO
ALTER DATABASE test_base
REMOVE FILEGROUP FileGroup2
GO
ALTER DATABASE  test_base
REMOVE FILE file5
GO
ALTER DATABASE  test_base
REMOVE FILEGROUP FileGroup3 
GO
ALTER DATABASE test_base
MODIFY FILEGROUP "PRIMARY" DEFAULT
GO
ALTER DATABASE test_base
ADD LOG FILE
(NAME = logfile1,
FILENAME = 'E:\ALBA\DB2018\logfile1.ldf'),
(NAME = logdile2,
FILENAME = 'E:\ALBA\DB2018\logfile2.ldf');
GO